// <auto-generated />
namespace VidlyApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class changingIdincustomertablemembershptType : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changingIdincustomertablemembershptType));
        
        string IMigrationMetadata.Id
        {
            get { return "201712310646056_changing Id in customer table membershptType"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
